markdown:         kramdown
highlighter:      pygments
permalink:        /:categories/:year/:month/:day/:title/

title:            "CevinJohnny's Blog"
url:              http://cevinjohnny.github.io/
feed:             /feed.xml
author:
    name:         CevinJohnny
    twitter:      
    key:           
description:      "."
copyright:        "CopryRight GuoJing 2012-2012 by GitHub and Jekyll"
headdesc:         "CevinJohnny的博客，关于设计，开发以及生活。"
headkeys:         "设计,开发,思考,生活,豆瓣,读书,电影,音乐,游记"